[package]
name = "tokio_hello"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.43", features = ["full"] }
mini-redis = "0.4"

[[example]]
name = "example"
path = "examples/*"
