# workspace = { members = ["链接系统库"] }
[package]
name = "hello-from-generated-code"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
