[package]
name = "hello_macro"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello_macro_derive = { path = "./hello_macro_derive" }
syn = "2.0.37"
