[package]
name = "错误处理与格式化输出"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sayhello_lib = { path = "E:/Doraemon/IT/Rust/study/sayhello_lib" }
thiserror = "1.0"
anyhow = "1.0"
